apiVersion: v1
kind: Secret
metadata:
  name: litellm-env
  namespace: nuwa
type: Opaque
data:
  # Note: Values should be base64 encoded
  # Use the update-env.sh script to manage environment variables securely
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: nuwa
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        args:
        - "--config"
        - "/app/config.yaml"
        - "--detailed_debug"
        ports:
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: litellm-env
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  namespace: nuwa
spec:
  type: NodePort
  selector:
    app: litellm
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litellm-ingress
  namespace: nuwa
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "litellm-ingress-static-ip" 
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "litellm-cert"
spec:
  rules:
  - host: litellm.nuwa.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litellm-service
            port: 
              number: 4000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: litellm-cert
  namespace: nuwa
spec:
  domains:
  - litellm.nuwa.dev