export default {
  separator1: { type: "separator", title: "Introduction" },
  index: "Overview",
  usecases: "Use Cases",
  separator2: { type: "separator", title: "Core Concepts" },
  architecture: "Architecture",
  cap: "Cap",
  payment: "Payment",
  "mcp-compatibility": "MCP Compatibility",
  "a2a-compatibility": "A2A Compatibility",
  identity: "Identity",
  wallet: "Wallet",
  "agent-state": "Agent State",
  separator3: { type: "separator", title: "Reference" },
  faq: "FAQ",
  nips: "NIPs",
};
